- build: 0.2.1
  image:
    - mesoscloud/haproxy-marathon:0.2.1
    - mesoscloud/haproxy-marathon:latest

- build: 0.2.0
  image:
    - mesoscloud/haproxy-marathon:0.2.0

- build: 0.1.1
  image:
    - mesoscloud/haproxy-marathon:0.1.1

- build: 0.1.0
  image:
    - mesoscloud/haproxy-marathon:0.1.0


- tests:
    - cmd: python -m doctest ./app.py
