- build: 0.1.0/ubuntu/14.04
  image:
    - mesoscloud/haproxy-marathon:0.1.0-ubuntu-14.04
    - mesoscloud/haproxy-marathon:0.1.0-ubuntu
    - mesoscloud/haproxy-marathon:0.1.0
    - mesoscloud/haproxy-marathon:latest


- tests:
    - cmd: python -m doctest ./init.py
